### ISSUE TITLE
Package Maintainance

### ISSUE THREAD

**Issue by rajatsharma** [vihanb/babel-plugin-loop-optimizer#11]
Hey,
Your readme says, `If anyone wishes to pick this up leave an issue and I can give access`, I was looking for maintaining this package and upgrading this package for babel 7. I would be happy if you give me access.

Thanks.

**Comment by vihanb** [comment]
Hi, sorry for late reply. If you (or anyone else reading that is interested), is still interested in helping maintain this package. Please submit a pull request with desired changes made, and after that I'll transfer ownership

**Comment by rajatsharma** [comment]
Submitted Pull request https://github.com/vihanb/babel-plugin-loop-optimizer/pull/12

**Comment by vihanb** [comment]
@rajatsharma thanks for PR I have invited you as a contributor. Let me know your npm id, so I can add you as a contributor on the NPM package too

**Comment by rajatsharma** [comment]
Hey, my npmId is `rajatsharma`
