### ISSUE TITLE
lodash.js (_.map) code ending get messed up 

### ISSUE THREAD

**Issue by jeanroldao** [vihanb/babel-plugin-loop-optimizer#4]
Hi, I like this plugin, but unfortunately it is messing up with lodash.
For example, 
var list = [1, 2, 3];
var list2 =_.map(list, n => n * 2);

This code doesn't even run after the optimization. I probably should not use lodash at all, but there is too many places already using it in my project.
This plugin has potential, I wish there was some configuration to make it compatible with lodash.

Thank you.

**Comment by vihanb** [comment]
For now you can add `// O: KEEP` above that line with the mao but it'll push a fix ASAP for this

**Comment by jeanroldao** [comment]
Hi, thanks for your reply, as I said in my project there is already a lot of _.map, more than 200 uses when I searched in the repository, it is not easy to add that comment line to all places needed, when you push the fix I will be happy to test it again, thank you.

**Comment by vihanb** [comment]
Okay, I've pushed a new version 1.4.0 to NPM, this just checks a `.map(...)` call has exactly one argument before it converts it. Let me know if this works and I can close this issue

**Comment by jeanroldao** [comment]
Hi, sorry the delay, I got some issues with my computer, now I tested it and it is working with my projected without needing to add the comment flag.
Thank you! :)
